export const packageSignals = {
  "generatedAt": "2026-05-23T13:21:18.032Z",
  "totals": {
    "downloadsLastWeek": 1663,
    "stars": 0,
    "openIssues": 0
  },
  "packages": [
    {
      "name": "array-table-kit",
      "npmUrl": "https://www.npmjs.com/package/array-table-kit",
      "githubUrl": "https://github.com/Recoveredd/array-table-kit",
      "downloadsLastWeek": 14,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.2.3",
      "pushedAt": "2026-05-13T15:23:58Z",
      "errors": []
    },
    {
      "name": "caption-track-doctor-kit",
      "npmUrl": "https://www.npmjs.com/package/caption-track-doctor-kit",
      "githubUrl": "https://github.com/Recoveredd/caption-track-doctor-kit",
      "downloadsLastWeek": 21,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:55Z",
      "errors": []
    },
    {
      "name": "color-nearest-match-kit",
      "npmUrl": "https://www.npmjs.com/package/color-nearest-match-kit",
      "githubUrl": "https://github.com/Recoveredd/color-nearest-match-kit",
      "downloadsLastWeek": 135,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:06Z",
      "errors": []
    },
    {
      "name": "crontab-timer-migration-kit",
      "npmUrl": "https://www.npmjs.com/package/crontab-timer-migration-kit",
      "githubUrl": "https://github.com/Recoveredd/crontab-timer-migration-kit",
      "downloadsLastWeek": 21,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:54Z",
      "errors": []
    },
    {
      "name": "css-font-shorthand-kit",
      "npmUrl": "https://www.npmjs.com/package/css-font-shorthand-kit",
      "githubUrl": "https://github.com/Recoveredd/css-font-shorthand-kit",
      "downloadsLastWeek": 8,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-14T11:50:29Z",
      "errors": []
    },
    {
      "name": "css-media-query-match-kit",
      "npmUrl": "https://www.npmjs.com/package/css-media-query-match-kit",
      "githubUrl": "https://github.com/Recoveredd/css-media-query-match-kit",
      "downloadsLastWeek": 123,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:05Z",
      "errors": []
    },
    {
      "name": "currency-code-symbol-kit",
      "npmUrl": "https://www.npmjs.com/package/currency-code-symbol-kit",
      "githubUrl": "https://github.com/Recoveredd/currency-code-symbol-kit",
      "downloadsLastWeek": 117,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:08Z",
      "errors": []
    },
    {
      "name": "data-url-kit",
      "npmUrl": "https://www.npmjs.com/package/data-url-kit",
      "githubUrl": "https://github.com/Recoveredd/data-url-kit",
      "downloadsLastWeek": 23,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.2",
      "pushedAt": "2026-05-14T17:28:35Z",
      "errors": []
    },
    {
      "name": "file-extension-inspect-kit",
      "npmUrl": "https://www.npmjs.com/package/file-extension-inspect-kit",
      "githubUrl": "https://github.com/Recoveredd/file-extension-inspect-kit",
      "downloadsLastWeek": 120,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:10Z",
      "errors": []
    },
    {
      "name": "filepath-validator-kit",
      "npmUrl": "https://www.npmjs.com/package/filepath-validator-kit",
      "githubUrl": "https://github.com/Recoveredd/filepath-validator-kit",
      "downloadsLastWeek": 9,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-13T23:17:35Z",
      "errors": []
    },
    {
      "name": "frontmatter-kit",
      "npmUrl": "https://www.npmjs.com/package/frontmatter-kit",
      "githubUrl": "https://github.com/Recoveredd/frontmatter-kit",
      "downloadsLastWeek": 10,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.1",
      "pushedAt": "2026-05-13T15:23:58Z",
      "errors": []
    },
    {
      "name": "har-redaction-kit",
      "npmUrl": "https://www.npmjs.com/package/har-redaction-kit",
      "githubUrl": "https://github.com/Recoveredd/har-redaction-kit",
      "downloadsLastWeek": 17,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:48Z",
      "errors": []
    },
    {
      "name": "hex-color-token-kit",
      "npmUrl": "https://www.npmjs.com/package/hex-color-token-kit",
      "githubUrl": "https://github.com/Recoveredd/hex-color-token-kit",
      "downloadsLastWeek": 24,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.1",
      "pushedAt": "2026-05-14T17:28:36Z",
      "errors": []
    },
    {
      "name": "hex-grid-kit",
      "npmUrl": "https://www.npmjs.com/package/hex-grid-kit",
      "githubUrl": "https://github.com/Recoveredd/hex-grid-kit",
      "downloadsLastWeek": 10,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-14T11:50:30Z",
      "errors": []
    },
    {
      "name": "http-accept-language-kit",
      "npmUrl": "https://www.npmjs.com/package/http-accept-language-kit",
      "githubUrl": "https://github.com/Recoveredd/http-accept-language-kit",
      "downloadsLastWeek": 133,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:02Z",
      "errors": []
    },
    {
      "name": "http-cache-control-kit",
      "npmUrl": "https://www.npmjs.com/package/http-cache-control-kit",
      "githubUrl": "https://github.com/Recoveredd/http-cache-control-kit",
      "downloadsLastWeek": 139,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:00Z",
      "errors": []
    },
    {
      "name": "http-link-header-kit",
      "npmUrl": "https://www.npmjs.com/package/http-link-header-kit",
      "githubUrl": "https://github.com/Recoveredd/http-link-header-kit",
      "downloadsLastWeek": 17,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:58Z",
      "errors": []
    },
    {
      "name": "human-duration-parse-kit",
      "npmUrl": "https://www.npmjs.com/package/human-duration-parse-kit",
      "githubUrl": "https://github.com/Recoveredd/human-duration-parse-kit",
      "downloadsLastWeek": 8,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-14T11:50:30Z",
      "errors": []
    },
    {
      "name": "import-specifier-scan-kit",
      "npmUrl": "https://www.npmjs.com/package/import-specifier-scan-kit",
      "githubUrl": "https://github.com/Recoveredd/import-specifier-scan-kit",
      "downloadsLastWeek": 23,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.1",
      "pushedAt": "2026-05-14T17:28:35Z",
      "errors": []
    },
    {
      "name": "jmx-k6-migration-kit",
      "npmUrl": "https://www.npmjs.com/package/jmx-k6-migration-kit",
      "githubUrl": "https://github.com/Recoveredd/jmx-k6-migration-kit",
      "downloadsLastWeek": 7,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-14T11:50:30Z",
      "errors": []
    },
    {
      "name": "json-csv-kit",
      "npmUrl": "https://www.npmjs.com/package/json-csv-kit",
      "githubUrl": "https://github.com/Recoveredd/json-csv-kit",
      "downloadsLastWeek": 8,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.1",
      "pushedAt": "2026-05-13T15:23:58Z",
      "errors": []
    },
    {
      "name": "json-html-kit",
      "npmUrl": "https://www.npmjs.com/package/json-html-kit",
      "githubUrl": "https://github.com/Recoveredd/json-html-kit",
      "downloadsLastWeek": 12,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.4.2",
      "pushedAt": "2026-05-13T15:23:58Z",
      "errors": []
    },
    {
      "name": "junit-report-doctor-kit",
      "npmUrl": "https://www.npmjs.com/package/junit-report-doctor-kit",
      "githubUrl": "https://github.com/Recoveredd/junit-report-doctor-kit",
      "downloadsLastWeek": 21,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:51Z",
      "errors": []
    },
    {
      "name": "large-log-viewer-kit",
      "npmUrl": "https://www.npmjs.com/package/large-log-viewer-kit",
      "githubUrl": "https://github.com/Recoveredd/large-log-viewer-kit",
      "downloadsLastWeek": 18,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:47Z",
      "errors": []
    },
    {
      "name": "lcov-trace-doctor-kit",
      "npmUrl": "https://www.npmjs.com/package/lcov-trace-doctor-kit",
      "githubUrl": "https://github.com/Recoveredd/lcov-trace-doctor-kit",
      "downloadsLastWeek": 16,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:52Z",
      "errors": []
    },
    {
      "name": "localized-price-parse-kit",
      "npmUrl": "https://www.npmjs.com/package/localized-price-parse-kit",
      "githubUrl": "https://github.com/Recoveredd/localized-price-parse-kit",
      "downloadsLastWeek": 8,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-14T11:50:30Z",
      "errors": []
    },
    {
      "name": "murmur-string-hash-kit",
      "npmUrl": "https://www.npmjs.com/package/murmur-string-hash-kit",
      "githubUrl": "https://github.com/Recoveredd/murmur-string-hash-kit",
      "downloadsLastWeek": 105,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:09Z",
      "errors": []
    },
    {
      "name": "node-lockfile-doctor-kit",
      "npmUrl": "https://www.npmjs.com/package/node-lockfile-doctor-kit",
      "githubUrl": "https://github.com/Recoveredd/node-lockfile-doctor-kit",
      "downloadsLastWeek": 19,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:49Z",
      "errors": []
    },
    {
      "name": "number-range-list-kit",
      "npmUrl": "https://www.npmjs.com/package/number-range-list-kit",
      "githubUrl": "https://github.com/Recoveredd/number-range-list-kit",
      "downloadsLastWeek": 7,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-14T11:27:22Z",
      "errors": []
    },
    {
      "name": "numeric-unit-parse-kit",
      "npmUrl": "https://www.npmjs.com/package/numeric-unit-parse-kit",
      "githubUrl": "https://github.com/Recoveredd/numeric-unit-parse-kit",
      "downloadsLastWeek": 122,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:11Z",
      "errors": []
    },
    {
      "name": "object-key-paths",
      "npmUrl": "https://www.npmjs.com/package/object-key-paths",
      "githubUrl": "https://github.com/Recoveredd/object-key-paths",
      "downloadsLastWeek": 9,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.1",
      "pushedAt": "2026-05-13T15:23:58Z",
      "errors": []
    },
    {
      "name": "object-path-kit",
      "npmUrl": "https://www.npmjs.com/package/object-path-kit",
      "githubUrl": "https://github.com/Recoveredd/object-path-kit",
      "downloadsLastWeek": 15,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.3",
      "pushedAt": "2026-05-13T15:23:58Z",
      "errors": []
    },
    {
      "name": "package-author-parse-kit",
      "npmUrl": "https://www.npmjs.com/package/package-author-parse-kit",
      "githubUrl": "https://github.com/Recoveredd/package-author-parse-kit",
      "downloadsLastWeek": 131,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:04Z",
      "errors": []
    },
    {
      "name": "proto-form-kit",
      "npmUrl": "https://www.npmjs.com/package/proto-form-kit",
      "githubUrl": "https://github.com/Recoveredd/proto-form-kit",
      "downloadsLastWeek": 11,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-14T11:50:30Z",
      "errors": []
    },
    {
      "name": "retry-delay-plan-kit",
      "npmUrl": "https://www.npmjs.com/package/retry-delay-plan-kit",
      "githubUrl": "https://github.com/Recoveredd/retry-delay-plan-kit",
      "downloadsLastWeek": 118,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-16T15:12:03Z",
      "errors": []
    },
    {
      "name": "robots-txt-kit",
      "npmUrl": "https://www.npmjs.com/package/robots-txt-kit",
      "githubUrl": "https://github.com/Recoveredd/robots-txt-kit",
      "downloadsLastWeek": 20,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:57Z",
      "errors": []
    },
    {
      "name": "svg-ast-kit",
      "npmUrl": "https://www.npmjs.com/package/svg-ast-kit",
      "githubUrl": "https://github.com/Recoveredd/svg-ast-kit",
      "downloadsLastWeek": 7,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.1",
      "pushedAt": "2026-05-13T15:23:59Z",
      "errors": []
    },
    {
      "name": "systemd-unit-doctor-kit",
      "npmUrl": "https://www.npmjs.com/package/systemd-unit-doctor-kit",
      "githubUrl": "https://github.com/Recoveredd/systemd-unit-doctor-kit",
      "downloadsLastWeek": 16,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.0",
      "pushedAt": "2026-05-15T08:28:53Z",
      "errors": []
    },
    {
      "name": "terminal-table-kit",
      "npmUrl": "https://www.npmjs.com/package/terminal-table-kit",
      "githubUrl": "https://github.com/Recoveredd/terminal-table-kit",
      "downloadsLastWeek": 11,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.2",
      "pushedAt": "2026-05-13T15:23:59Z",
      "errors": []
    },
    {
      "name": "text-similarity-kit",
      "npmUrl": "https://www.npmjs.com/package/text-similarity-kit",
      "githubUrl": "https://github.com/Recoveredd/text-similarity-kit",
      "downloadsLastWeek": 10,
      "stars": 0,
      "openIssues": 0,
      "latestVersion": "0.1.1",
      "pushedAt": "2026-05-13T15:23:58Z",
      "errors": []
    }
  ]
} as const;
